### ISSUE TITLE
Reveal Phase 1 Powered Dashboards

### ISSUE THREAD

**Issue by moshthepitt** [onaio/mspray#440]
For reveal phase 1, we need to demonstrate that we can generate the same mSpray spray data related dashboards.  This issue attempts to do just that.

### Data Source

The assumption that this issue makes is that Nifi will send spray data to mSpray.  This spray data will be derived (by Nifi) from Tasks in OpenSRP (more info. on these: https://github.com/OpenSRP/opensrp-server-core/issues/4) and will include at least:

- the spray operator - an id of a spray operator in the mspray database
- the location: this might be an id of an existing location in the mspray database, or coordinates (TBD)
- the spray status
- the datetime

The exact structure of what we receive from Nifi is not known at this point, but I believe that we can work with the above.

### The Process

Once mSpray receives the data from Nifi, it will then create a `SprayDay object`.  In theory, the successful creation of this SprayDay object is all that we have to achieve for this issue as the rest of mSpray works around SprayDay objects and the dashboards should just work.

### Tasks

- [x] Setup the mSpray database for reveal, including all locations (taken from mSpray 2018 season) and spray operators (Team Leads, Team Lead Assistants and Spray Operators)
- [x] Create an mSpray endpoint that receives spray data from Nifi
- [x] Add a function that converts that spray data into SprayDay objects
- [ ] Optionally write functions that can ask Nifi for updated/missing spray data
- [x] Ensure that the mSray dashboards work well with this reveal spray data.  This might include modifying the views and/or templates to deal with any missing data that the current mSpray system expects

**Comment by moshthepitt** [comment]
Wontfix: Optionally write functions that can ask Nifi for updated/missing spray data
